/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labb0;

public class App {
   
    public static void main(String[] args) {
        Characters characters = new Characters();

        System.out.println(characters.morseAlphabet);

        String name = "marcus";
        


}
}
