/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labb0;

import java.util.HashMap;
import java.util.Map;

public class App {
   
    public static void main(String[] args) {
        Characters characters = new Characters();

        

        String name = "marcus";

        final Map<String, String> arrayMap = new HashMap<String, String>(); 
        for (int i = 0; i < characters.swedishAlphabet.length; i++) {
            arrayMap.put(characters.swedishAlphabet[i], characters.morseAlphabet[i]);

            System.out.println(arrayMap);
        }

        /* System.out.println(arrayMap); */
}
}
